# 1. reading the dataset

In [1]:
import pandas as pd
import numpy as np
df = pd.read_csv(r"1.csv")

info about the dataset

In [2]:
df

,Unnamed: 0,ts,uid,id.orig_h,id.orig_p,id.resp_h,id.resp_p,proto,service,duration,...,conn_state,local_orig,local_resp,missed_bytes,history,orig_pkts,orig_ip_bytes,resp_pkts,resp_ip_bytes,Label
0,0,1525879831,CUmrqr4svHuSXJy5z7,192.168.100.103,51524,65.127.233.163,23,tcp,-,2.999051,...,S0,-,-,0,S,3,180,0,0,(empty) Malicious PartOfAHorizontalPortScan
1,1,1525879831,CH98aB3s1kJeq6SFOc,192.168.100.103,56305,63.150.16.171,23,tcp,-,-,...,S0,-,-,0,S,1,60,0,0,(empty) Malicious PartOfAHorizontalPortScan
2,2,1525879831,C3GBTkINvXNjVGtN5,192.168.100.103,41101,111.40.23.49,23,tcp,-,-,...,S0,-,-,0,S,1,60,0,0,(empty) Malicious PartOfAHorizontalPortScan
3,3,1525879832,CDe43c1PtgynajGI6,192.168.100.103,60905,131.174.215.147,23,tcp,-,2.998796,...,S0,-,-,0,S,3,180,0,0,(empty) Malicious PartOfAHorizontalPortScan
4,4,1525879832,CJaDcG3MZzvf1YVYI4,192.168.100.103,44301,91.42.47.63,23,tcp,-,-,...,S0,-,-,0,S,1,60,0,0,(empty) Malicious PartOfAHorizontalPortScan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1008743,1008743,1526282655,CUyBg1WA04SBmf3ah,192.168.100.103,43763,16.219.83.137,64906,udp,-,-,...,S0,-,-,0,D,1,40,0,0,(empty) Benign -
1008744,1008744,1526282682,CvaIoX2b9VynuYieBf,192.168.100.103,43763,100.57.245.196,39435,udp,-,-,...,S0,-,-,0,D,1,40,0,0,(empty) Benign -
1008745,1008745,1526282625,CVHrUzIUN0mW5lQsl,192.168.100.103,43763,249.99.119.9,26169,udp,-,-,...,S0,-,-,0,D,1,40,0,0,(empty) Benign -
1008746,1008746,1526282676,CkGlnL2pxzlusrFlLj,192.168.100.103,43763,205.103.167.192,18241,udp,-,-,...,S0,-,-,0,D,1,40,0,0,(empty) Benign -
1008747,1008747,1526282660,CoOjVZ1zw3pWf7a9n5,192.168.100.103,43763,23.70.168.160,16854,udp,-,-,...,S0,-,-,0,D,1,40,0,0,(empty) Benign -

# 2. drop rows that have nan values in the label class

In [3]:
df.drop(df.index[df['Label'] == 'nan'], inplace = True)

# 3. make all the different benign names as benign

In [4]:
df['Label']=df['Label'].replace('   benign   ','benign')
df['Label']=df['Label'].replace('(empty)   Benign   -','benign')
df['Label']=df['Label'].replace('-   Benign   -','benign')
df['Label']=df['Label'].replace('-   benign   -','benign')
df['Label']=df['Label'].replace('(empty)   benign   -','benign')

# 4. see the values of the class and their counts

In [5]:
df["Label"].value_counts()

Label
(empty)   Malicious   PartOfAHorizontalPortScan    539465
benign                                             469275
(empty)   Malicious   C&C                               8
Name: count, dtype: int64

# 5. Label encoding: benign as 0 , malicious as 1

In [6]:
# Transform Label column
df['Label'] = np.where(df['Label'] == 'benign', 0, 1)

verify from the classes counts ( benign still 469275)

In [7]:
df["Label"].value_counts()

Label
1    539473
0    469275
Name: count, dtype: int64

In [8]:
df

,Unnamed: 0,ts,uid,id.orig_h,id.orig_p,id.resp_h,id.resp_p,proto,service,duration,...,conn_state,local_orig,local_resp,missed_bytes,history,orig_pkts,orig_ip_bytes,resp_pkts,resp_ip_bytes,Label
0,0,1525879831,CUmrqr4svHuSXJy5z7,192.168.100.103,51524,65.127.233.163,23,tcp,-,2.999051,...,S0,-,-,0,S,3,180,0,0,1
1,1,1525879831,CH98aB3s1kJeq6SFOc,192.168.100.103,56305,63.150.16.171,23,tcp,-,-,...,S0,-,-,0,S,1,60,0,0,1
2,2,1525879831,C3GBTkINvXNjVGtN5,192.168.100.103,41101,111.40.23.49,23,tcp,-,-,...,S0,-,-,0,S,1,60,0,0,1
3,3,1525879832,CDe43c1PtgynajGI6,192.168.100.103,60905,131.174.215.147,23,tcp,-,2.998796,...,S0,-,-,0,S,3,180,0,0,1
4,4,1525879832,CJaDcG3MZzvf1YVYI4,192.168.100.103,44301,91.42.47.63,23,tcp,-,-,...,S0,-,-,0,S,1,60,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1008743,1008743,1526282655,CUyBg1WA04SBmf3ah,192.168.100.103,43763,16.219.83.137,64906,udp,-,-,...,S0,-,-,0,D,1,40,0,0,0
1008744,1008744,1526282682,CvaIoX2b9VynuYieBf,192.168.100.103,43763,100.57.245.196,39435,udp,-,-,...,S0,-,-,0,D,1,40,0,0,0
1008745,1008745,1526282625,CVHrUzIUN0mW5lQsl,192.168.100.103,43763,249.99.119.9,26169,udp,-,-,...,S0,-,-,0,D,1,40,0,0,0
1008746,1008746,1526282676,CkGlnL2pxzlusrFlLj,192.168.100.103,43763,205.103.167.192,18241,udp,-,-,...,S0,-,-,0,D,1,40,0,0,0
1008747,1008747,1526282660,CoOjVZ1zw3pWf7a9n5,192.168.100.103,43763,23.70.168.160,16854,udp,-,-,...,S0,-,-,0,D,1,40,0,0,0

# 6. Features Encoding

In [9]:
#Encodeing Features
import pandas as pd

encoding_map = {
    "proto": {
        "icmp": 0,
        "tcp": 1,
        "udp": 2,
        "UNKNOWN": -1
    },
    "service": {
        "-": 0,
        "dhcp": 1,
        "dns": 2,
        "http": 3,
        "ssh": 4,
        "ssl": 5,
        "irc": 6,
        "UNKNOWN": -1
    },
    "conn_state": {
         "S0": 0,
         "S1": 1,
         "S2": 2,
         "S3": 3,
         "SF": 4,
         "REJ": 5,
         "RSTO": 6,
         "RSTR": 7,
         "RSTOS0": 8,
         "RSTRH": 9,
         "SH": 10,
         "SHR": 11,
         "OTH": 12,
         "UNKNOWN": -1
    }
}

def encode_categorical(df, encoding_map):
    """
    Convert categorical columns in DataFrame to numerical values using the encoding map.
    Unknown values will be mapped to -1.
    """
    for col in encoding_map:
        if col in df.columns:
            df[col] = df[col].map(encoding_map[col]).fillna(-1).astype(int)
    return df

In [10]:

df= encode_categorical(df, encoding_map)

In [11]:
# df['Label'] = df['Label'].replace({
#     '-   Benign   -': 0,
#     '-   Malicious   DDoS': 1,
#     '-   Malicious   C&C': 1,
#     '-   Malicious   PartOfAHorizontalPortScan   -':1,
#     # Add other malicious variants
# })

verifying:

In [12]:
df

,Unnamed: 0,ts,uid,id.orig_h,id.orig_p,id.resp_h,id.resp_p,proto,service,duration,...,conn_state,local_orig,local_resp,missed_bytes,history,orig_pkts,orig_ip_bytes,resp_pkts,resp_ip_bytes,Label
0,0,1525879831,CUmrqr4svHuSXJy5z7,192.168.100.103,51524,65.127.233.163,23,1,0,2.999051,...,0,-,-,0,S,3,180,0,0,1
1,1,1525879831,CH98aB3s1kJeq6SFOc,192.168.100.103,56305,63.150.16.171,23,1,0,-,...,0,-,-,0,S,1,60,0,0,1
2,2,1525879831,C3GBTkINvXNjVGtN5,192.168.100.103,41101,111.40.23.49,23,1,0,-,...,0,-,-,0,S,1,60,0,0,1
3,3,1525879832,CDe43c1PtgynajGI6,192.168.100.103,60905,131.174.215.147,23,1,0,2.998796,...,0,-,-,0,S,3,180,0,0,1
4,4,1525879832,CJaDcG3MZzvf1YVYI4,192.168.100.103,44301,91.42.47.63,23,1,0,-,...,0,-,-,0,S,1,60,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1008743,1008743,1526282655,CUyBg1WA04SBmf3ah,192.168.100.103,43763,16.219.83.137,64906,2,0,-,...,0,-,-,0,D,1,40,0,0,0
1008744,1008744,1526282682,CvaIoX2b9VynuYieBf,192.168.100.103,43763,100.57.245.196,39435,2,0,-,...,0,-,-,0,D,1,40,0,0,0
1008745,1008745,1526282625,CVHrUzIUN0mW5lQsl,192.168.100.103,43763,249.99.119.9,26169,2,0,-,...,0,-,-,0,D,1,40,0,0,0
1008746,1008746,1526282676,CkGlnL2pxzlusrFlLj,192.168.100.103,43763,205.103.167.192,18241,2,0,-,...,0,-,-,0,D,1,40,0,0,0
1008747,1008747,1526282660,CoOjVZ1zw3pWf7a9n5,192.168.100.103,43763,23.70.168.160,16854,2,0,-,...,0,-,-,0,D,1,40,0,0,0

In [13]:
import pandas as pd
import numpy as np
from scipy.stats import pointbiserialr, chi2_contingency
from sklearn.feature_selection import mutual_info_classif

# Check dtypes
print("Data Types:\n", df.dtypes)

Data Types:
 Unnamed: 0        int64
ts                int64
uid              object
id.orig_h        object
id.orig_p         int64
id.resp_h        object
id.resp_p         int64
proto             int32
service           int32
duration         object
orig_bytes       object
resp_bytes       object
conn_state        int32
local_orig       object
local_resp       object
missed_bytes      int64
history          object
orig_pkts         int64
orig_ip_bytes     int64
resp_pkts         int64
resp_ip_bytes     int64
Label             int32
dtype: object

# 7. drop unneccessary features to prevent overfitting

In [14]:
df = df.drop('Unnamed: 0', axis=1)  
df = df.drop('ts', axis=1)  
df = df.drop('uid', axis=1)  
df = df.drop('local_orig', axis=1)  
df = df.drop('local_resp', axis=1)  
df = df.drop('id.orig_h', axis=1)  
df = df.drop('id.resp_h', axis=1)  
df = df.drop('id.orig_p', axis=1)  
df = df.drop('history', axis=1)

knowing the types to knwo what we must change

In [15]:
df.dtypes

id.resp_p         int64
proto             int32
service           int32
duration         object
orig_bytes       object
resp_bytes       object
conn_state        int32
missed_bytes      int64
orig_pkts         int64
orig_ip_bytes     int64
resp_pkts         int64
resp_ip_bytes     int64
Label             int32
dtype: object

# 8. convert to numeric

In [16]:
# Convert "numeric-as-object" columns to float/int
cols_to_convert = ['duration', 'orig_bytes', 'resp_bytes']
df[cols_to_convert] = df[cols_to_convert].apply(pd.to_numeric, errors='coerce')  # 'coerce' sets invalid parsing as NaN

verifying:

In [17]:
df.dtypes

id.resp_p          int64
proto              int32
service            int32
duration         float64
orig_bytes       float64
resp_bytes       float64
conn_state         int32
missed_bytes       int64
orig_pkts          int64
orig_ip_bytes      int64
resp_pkts          int64
resp_ip_bytes      int64
Label              int32
dtype: object

In [20]:
df

,id.resp_p,proto,service,duration,orig_bytes,resp_bytes,conn_state,missed_bytes,orig_pkts,orig_ip_bytes,resp_pkts,resp_ip_bytes,Label
0,23,1,0,2.999051,0.0,0.0,0,0,3,180,0,0,1
1,23,1,0,NaN,NaN,NaN,0,0,1,60,0,0,1
2,23,1,0,NaN,NaN,NaN,0,0,1,60,0,0,1
3,23,1,0,2.998796,0.0,0.0,0,0,3,180,0,0,1
4,23,1,0,NaN,NaN,NaN,0,0,1,60,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1008743,64906,2,0,NaN,NaN,NaN,0,0,1,40,0,0,0
1008744,39435,2,0,NaN,NaN,NaN,0,0,1,40,0,0,0
1008745,26169,2,0,NaN,NaN,NaN,0,0,1,40,0,0,0
1008746,18241,2,0,NaN,NaN,NaN,0,0,1,40,0,0,0
1008747,16854,2,0,NaN,NaN,NaN,0,0,1,40,0,0,0

In [21]:
print(df.dtypes)

id.resp_p          int64
proto              int32
service            int32
duration         float64
orig_bytes       float64
resp_bytes       float64
conn_state         int32
missed_bytes       int64
orig_pkts          int64
orig_ip_bytes      int64
resp_pkts          int64
resp_ip_bytes      int64
Label              int32
dtype: object

In [22]:
print(df[['id.resp_p', 'missed_bytes', 'orig_pkts']].describe())

          id.resp_p  missed_bytes     orig_pkts
count  1.008748e+06     1008748.0  1.008748e+06
mean   1.609771e+04           0.0  1.496242e+00
std    1.956280e+04           0.0  1.741176e+00
min    0.000000e+00           0.0  0.000000e+00
25%    2.300000e+01           0.0  1.000000e+00
50%    8.080000e+03           0.0  1.000000e+00
75%    2.818025e+04           0.0  1.000000e+00
max    6.553500e+04           0.0  6.000000e+01

In [23]:
df["Label"].value_counts()

Label
1    539473
0    469275
Name: count, dtype: int64

In [25]:
df

,id.resp_p,proto,service,duration,orig_bytes,resp_bytes,conn_state,missed_bytes,orig_pkts,orig_ip_bytes,resp_pkts,resp_ip_bytes,Label
0,23,1,0,2.999051,0.0,0.0,0,0,3,180,0,0,1
1,23,1,0,NaN,NaN,NaN,0,0,1,60,0,0,1
2,23,1,0,NaN,NaN,NaN,0,0,1,60,0,0,1
3,23,1,0,2.998796,0.0,0.0,0,0,3,180,0,0,1
4,23,1,0,NaN,NaN,NaN,0,0,1,60,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1008743,64906,2,0,NaN,NaN,NaN,0,0,1,40,0,0,0
1008744,39435,2,0,NaN,NaN,NaN,0,0,1,40,0,0,0
1008745,26169,2,0,NaN,NaN,NaN,0,0,1,40,0,0,0
1008746,18241,2,0,NaN,NaN,NaN,0,0,1,40,0,0,0
1008747,16854,2,0,NaN,NaN,NaN,0,0,1,40,0,0,0

# 9. dealing with Nan values

In [26]:
import pandas as pd
import numpy as np

# Assuming df is your loaded DataFrame

# Calculate medians for non-S0 connections
non_s0_mask = df['conn_state'] != 0
medians = {
    'duration': df.loc[non_s0_mask, 'duration'].median(),
    'orig_bytes': df.loc[non_s0_mask, 'orig_bytes'].median(),
    'resp_bytes': df.loc[non_s0_mask, 'resp_bytes'].median()
}

# Only fill NaN values where conn_state == 0
for col in ['duration', 'orig_bytes', 'resp_bytes']:
    # For conn_state == 0: Fill ONLY NaNs with 0
    df.loc[(df['conn_state'] == 0) & (df[col].isna()), col] = 0
    
    # For conn_state != 0: Fill NaNs with their respective medians
    df.loc[(df['conn_state'] != 0) & (df[col].isna()), col] = medians[col]

# Verify the results
print("NaN values after imputation:")
print(df[['duration', 'orig_bytes', 'resp_bytes']].isna().sum())

NaN values after imputation:
duration      0
orig_bytes    0
resp_bytes    0
dtype: int64

In [27]:
df['Label'].isnull().values.any()

False

In [28]:
df

,id.resp_p,proto,service,duration,orig_bytes,resp_bytes,conn_state,missed_bytes,orig_pkts,orig_ip_bytes,resp_pkts,resp_ip_bytes,Label
0,23,1,0,2.999051,0.0,0.0,0,0,3,180,0,0,1
1,23,1,0,0.000000,0.0,0.0,0,0,1,60,0,0,1
2,23,1,0,0.000000,0.0,0.0,0,0,1,60,0,0,1
3,23,1,0,2.998796,0.0,0.0,0,0,3,180,0,0,1
4,23,1,0,0.000000,0.0,0.0,0,0,1,60,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1008743,64906,2,0,0.000000,0.0,0.0,0,0,1,40,0,0,0
1008744,39435,2,0,0.000000,0.0,0.0,0,0,1,40,0,0,0
1008745,26169,2,0,0.000000,0.0,0.0,0,0,1,40,0,0,0
1008746,18241,2,0,0.000000,0.0,0.0,0,0,1,40,0,0,0
1008747,16854,2,0,0.000000,0.0,0.0,0,0,1,40,0,0,0

# 10. saving the dataframe to .csv file format

In [29]:
df.to_csv(r"1cleaned.csv")