In [1]:
import pandas as pd
import numpy as np
df = pd.read_csv(r"49.csv")

C:\Users\Hussein Salloum\AppData\Local\Temp\ipykernel_11796\2727946029.py:3: DtypeWarning: Columns (9,10,11) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(r"49.csv")

In [2]:
df

,Unnamed: 0,ts,uid,id.orig_h,id.orig_p,id.resp_h,id.resp_p,proto,service,duration,...,conn_state,local_orig,local_resp,missed_bytes,history,orig_pkts,orig_ip_bytes,resp_pkts,resp_ip_bytes,tunnel_parents label detailed-label
0,0,1.551383e+09,Cnkx4U1xJgOIPooe2,192.168.1.193,51358,134.209.72.171,80,tcp,http,1.874424,...,SF,-,-,0,ShADadttfF,234,12994,285,418624,- Malicious FileDownload -
1,1,1.551383e+09,C5t6Kp1UnQyH7JCC45,192.168.1.193,51360,134.209.72.171,80,tcp,http,1.871487,...,SF,-,-,0,ShADadttfF,282,15702,282,412612,- Malicious FileDownload -
2,2,1.551383e+09,CRdXqi4p3HG1obs6xl,192.168.1.193,51362,134.209.72.171,80,tcp,http,2.376374,...,SF,-,-,0,ShADadttfF,174,9600,201,291562,- Malicious FileDownload -
3,3,1.551383e+09,Co7Sfi3KfjPoJwW5Kf,192.168.1.193,51364,134.209.72.171,80,tcp,-,3.092539,...,S0,-,-,0,S,6,360,0,0,- Benign -
4,4,1.551383e+09,CKaKqD34bwvqLUcID9,192.168.1.193,51364,134.209.72.171,80,tcp,http,1.35978,...,SF,-,-,0,ShADadttfF,178,9840,196,284806,- Malicious FileDownload -
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5410556,5410556,1.551410e+09,Ctc2If2AEpNehSWL2a,192.168.1.193,30535,217.48.18.213,8081,tcp,-,-,...,S0,-,-,0,S,1,40,0,0,- Malicious PartOfAHorizontalPortScan -
5410557,5410557,1.551383e+09,CJm7HCnrDfDREbMm7,192.168.1.193,50178,134.209.72.171,4554,tcp,-,26347.422164,...,S1,-,-,0,ShADad,1796,93758,1792,102154,- Malicious C&C-FileDownload
5410558,5410558,1.551410e+09,C5uG6C4AFRl77HCJM9,192.168.1.193,52882,134.209.72.171,4554,tcp,-,0.304830,...,SF,-,-,0,ShADdfFr,10,558,8,430,- Malicious C&C
5410559,5410559,1.551410e+09,Cfdczo4DyzPUejtd0g,217.229.163.167,3,192.168.1.193,13,icmp,-,0.000005,...,OTH,-,-,0,-,2,112,0,0,- Benign -
5410560,5410560,1.551410e+09,C3W3yA44vwV6ovDa2j,14.1.5.94,11,192.168.1.193,0,icmp,-,0.000005,...,OTH,-,-,0,-,2,112,0,0,- Benign -

In [3]:
df = df.rename(columns={"tunnel_parents_label_detailedlabel": "tunnel_parents   label   detailed-label"})
df = df.rename(columns={"tunnel_parents   label   detailed-label": "Label"})
df = df.rename(columns={"idorig_h": "id.orig_h"})
df = df.rename(columns={"idorig_p": "id.orig_p"})
df = df.rename(columns={"idresp_p": "id.resp_p"})
df = df.rename(columns={"idresp_h": "id.resp_h"})
df.drop(df.index[df['Label'] == 'nan'], inplace = True)

In [4]:
df['Label']=df['Label'].replace('   benign   ','benign')
df['Label']=df['Label'].replace('(empty)   Benign   -','benign')
df['Label']=df['Label'].replace('-   Benign   -','benign')
df['Label']=df['Label'].replace('-   benign   -','benign')
df['Label']=df['Label'].replace('(empty)   benign   -','benign')

In [5]:
df["Label"].value_counts()

Label
-   Malicious   PartOfAHorizontalPortScan   -    5404959
benign                                              3665
-   Malicious   C&C                                 1922
-   Malicious   FileDownload   -                      14
-   Malicious   C&C-FileDownload                       1
Name: count, dtype: int64

In [6]:
# Transform Label column
df['Label'] = np.where(df['Label'] == 'benign', 0, 1)

In [7]:
df["Label"].value_counts()

Label
1    5406896
0       3665
Name: count, dtype: int64

In [8]:
df

,Unnamed: 0,ts,uid,id.orig_h,id.orig_p,id.resp_h,id.resp_p,proto,service,duration,...,conn_state,local_orig,local_resp,missed_bytes,history,orig_pkts,orig_ip_bytes,resp_pkts,resp_ip_bytes,Label
0,0,1.551383e+09,Cnkx4U1xJgOIPooe2,192.168.1.193,51358,134.209.72.171,80,tcp,http,1.874424,...,SF,-,-,0,ShADadttfF,234,12994,285,418624,1
1,1,1.551383e+09,C5t6Kp1UnQyH7JCC45,192.168.1.193,51360,134.209.72.171,80,tcp,http,1.871487,...,SF,-,-,0,ShADadttfF,282,15702,282,412612,1
2,2,1.551383e+09,CRdXqi4p3HG1obs6xl,192.168.1.193,51362,134.209.72.171,80,tcp,http,2.376374,...,SF,-,-,0,ShADadttfF,174,9600,201,291562,1
3,3,1.551383e+09,Co7Sfi3KfjPoJwW5Kf,192.168.1.193,51364,134.209.72.171,80,tcp,-,3.092539,...,S0,-,-,0,S,6,360,0,0,0
4,4,1.551383e+09,CKaKqD34bwvqLUcID9,192.168.1.193,51364,134.209.72.171,80,tcp,http,1.35978,...,SF,-,-,0,ShADadttfF,178,9840,196,284806,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5410556,5410556,1.551410e+09,Ctc2If2AEpNehSWL2a,192.168.1.193,30535,217.48.18.213,8081,tcp,-,-,...,S0,-,-,0,S,1,40,0,0,1
5410557,5410557,1.551383e+09,CJm7HCnrDfDREbMm7,192.168.1.193,50178,134.209.72.171,4554,tcp,-,26347.422164,...,S1,-,-,0,ShADad,1796,93758,1792,102154,1
5410558,5410558,1.551410e+09,C5uG6C4AFRl77HCJM9,192.168.1.193,52882,134.209.72.171,4554,tcp,-,0.304830,...,SF,-,-,0,ShADdfFr,10,558,8,430,1
5410559,5410559,1.551410e+09,Cfdczo4DyzPUejtd0g,217.229.163.167,3,192.168.1.193,13,icmp,-,0.000005,...,OTH,-,-,0,-,2,112,0,0,0
5410560,5410560,1.551410e+09,C3W3yA44vwV6ovDa2j,14.1.5.94,11,192.168.1.193,0,icmp,-,0.000005,...,OTH,-,-,0,-,2,112,0,0,0

In [9]:
#Encodeing Features
import pandas as pd

# Your predefined encoding dictionary
encoding_map = {
    "proto": {
        "icmp": 0,
        "tcp": 1,
        "udp": 2,
        "UNKNOWN": -1
    },
    "service": {
        "-": 0,
        "dhcp": 1,
        "dns": 2,
        "http": 3,
        "ssh": 4,
        "ssl": 5,
        "irc": 6,
        "UNKNOWN": -1
    },
    "conn_state": {
         "S0": 0,
         "S1": 1,
         "S2": 2,
         "S3": 3,
         "SF": 4,
         "REJ": 5,
         "RSTO": 6,
         "RSTR": 7,
         "RSTOS0": 8,
         "RSTRH": 9,
         "SH": 10,
         "SHR": 11,
         "OTH": 12,
         "UNKNOWN": -1
    }
}

def encode_categorical(df, encoding_map):
    """
    Convert categorical columns in DataFrame to numerical values using the encoding map.
    Unknown values will be mapped to -1.
    """
    for col in encoding_map:
        if col in df.columns:
            df[col] = df[col].map(encoding_map[col]).fillna(-1).astype(int)
    return df

In [10]:

df= encode_categorical(df, encoding_map)

In [12]:
df

,Unnamed: 0,ts,uid,id.orig_h,id.orig_p,id.resp_h,id.resp_p,proto,service,duration,...,conn_state,local_orig,local_resp,missed_bytes,history,orig_pkts,orig_ip_bytes,resp_pkts,resp_ip_bytes,Label
0,0,1.551383e+09,Cnkx4U1xJgOIPooe2,192.168.1.193,51358,134.209.72.171,80,1,3,1.874424,...,4,-,-,0,ShADadttfF,234,12994,285,418624,1
1,1,1.551383e+09,C5t6Kp1UnQyH7JCC45,192.168.1.193,51360,134.209.72.171,80,1,3,1.871487,...,4,-,-,0,ShADadttfF,282,15702,282,412612,1
2,2,1.551383e+09,CRdXqi4p3HG1obs6xl,192.168.1.193,51362,134.209.72.171,80,1,3,2.376374,...,4,-,-,0,ShADadttfF,174,9600,201,291562,1
3,3,1.551383e+09,Co7Sfi3KfjPoJwW5Kf,192.168.1.193,51364,134.209.72.171,80,1,0,3.092539,...,0,-,-,0,S,6,360,0,0,0
4,4,1.551383e+09,CKaKqD34bwvqLUcID9,192.168.1.193,51364,134.209.72.171,80,1,3,1.35978,...,4,-,-,0,ShADadttfF,178,9840,196,284806,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5410556,5410556,1.551410e+09,Ctc2If2AEpNehSWL2a,192.168.1.193,30535,217.48.18.213,8081,1,0,-,...,0,-,-,0,S,1,40,0,0,1
5410557,5410557,1.551383e+09,CJm7HCnrDfDREbMm7,192.168.1.193,50178,134.209.72.171,4554,1,0,26347.422164,...,1,-,-,0,ShADad,1796,93758,1792,102154,1
5410558,5410558,1.551410e+09,C5uG6C4AFRl77HCJM9,192.168.1.193,52882,134.209.72.171,4554,1,0,0.304830,...,4,-,-,0,ShADdfFr,10,558,8,430,1
5410559,5410559,1.551410e+09,Cfdczo4DyzPUejtd0g,217.229.163.167,3,192.168.1.193,13,0,0,0.000005,...,12,-,-,0,-,2,112,0,0,0
5410560,5410560,1.551410e+09,C3W3yA44vwV6ovDa2j,14.1.5.94,11,192.168.1.193,0,0,0,0.000005,...,12,-,-,0,-,2,112,0,0,0

In [13]:
import pandas as pd
import numpy as np
from scipy.stats import pointbiserialr, chi2_contingency
from sklearn.feature_selection import mutual_info_classif

# Check dtypes
print("Data Types:\n", df.dtypes)

Data Types:
 Unnamed: 0         int64
ts               float64
uid               object
id.orig_h         object
id.orig_p          int64
id.resp_h         object
id.resp_p          int64
proto              int32
service            int32
duration          object
orig_bytes        object
resp_bytes        object
conn_state         int32
local_orig        object
local_resp        object
missed_bytes       int64
history           object
orig_pkts          int64
orig_ip_bytes      int64
resp_pkts          int64
resp_ip_bytes      int64
Label              int32
dtype: object

In [14]:
df = df.drop('Unnamed: 0', axis=1)  
df = df.drop('ts', axis=1)  
df = df.drop('uid', axis=1)  
df = df.drop('local_orig', axis=1)  
df = df.drop('local_resp', axis=1)  
df = df.drop('id.orig_h', axis=1)  
df = df.drop('id.resp_h', axis=1)  
df = df.drop('id.orig_p', axis=1)  
df = df.drop('history', axis=1)

In [15]:
df.dtypes

id.resp_p         int64
proto             int32
service           int32
duration         object
orig_bytes       object
resp_bytes       object
conn_state        int32
missed_bytes      int64
orig_pkts         int64
orig_ip_bytes     int64
resp_pkts         int64
resp_ip_bytes     int64
Label             int32
dtype: object

In [16]:
# Convert "numeric-as-object" columns to float/int
cols_to_convert = ['duration', 'orig_bytes', 'resp_bytes']
df[cols_to_convert] = df[cols_to_convert].apply(pd.to_numeric, errors='coerce')  # 'coerce' sets invalid parsing as NaN

In [17]:
df.dtypes

id.resp_p          int64
proto              int32
service            int32
duration         float64
orig_bytes       float64
resp_bytes       float64
conn_state         int32
missed_bytes       int64
orig_pkts          int64
orig_ip_bytes      int64
resp_pkts          int64
resp_ip_bytes      int64
Label              int32
dtype: object

In [19]:
print(df.dtypes)

id.resp_p          int64
proto              int32
service            int32
duration         float64
orig_bytes       float64
resp_bytes       float64
conn_state         int32
missed_bytes       int64
orig_pkts          int64
orig_ip_bytes      int64
resp_pkts          int64
resp_ip_bytes      int64
Label              int32
dtype: object

In [20]:
df

,id.resp_p,proto,service,duration,orig_bytes,resp_bytes,conn_state,missed_bytes,orig_pkts,orig_ip_bytes,resp_pkts,resp_ip_bytes,Label
0,80,1,3,1.874424,149.0,198998.0,4,0,234,12994,285,418624,1
1,80,1,3,1.871487,151.0,198966.0,4,0,282,15702,282,412612,1
2,80,1,3,2.376374,148.0,140547.0,4,0,174,9600,201,291562,1
3,80,1,0,3.092539,0.0,0.0,0,0,6,360,0,0,0
4,80,1,3,1.359780,148.0,137299.0,4,0,178,9840,196,284806,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5410556,8081,1,0,NaN,NaN,NaN,0,0,1,40,0,0,1
5410557,4554,1,0,26347.422164,11.0,4413.0,1,0,1796,93758,1792,102154,1
5410558,4554,1,0,0.304830,11.0,11.0,4,0,10,558,8,430,1
5410559,13,0,0,0.000005,56.0,0.0,12,0,2,112,0,0,0
5410560,0,0,0,0.000005,56.0,0.0,12,0,2,112,0,0,0

In [21]:
print(df.dtypes)

id.resp_p          int64
proto              int32
service            int32
duration         float64
orig_bytes       float64
resp_bytes       float64
conn_state         int32
missed_bytes       int64
orig_pkts          int64
orig_ip_bytes      int64
resp_pkts          int64
resp_ip_bytes      int64
Label              int32
dtype: object

In [23]:
df["Label"].value_counts()

Label
1    5406896
0       3665
Name: count, dtype: int64

In [24]:
df

,id.resp_p,proto,service,duration,orig_bytes,resp_bytes,conn_state,missed_bytes,orig_pkts,orig_ip_bytes,resp_pkts,resp_ip_bytes,Label
0,80,1,3,1.874424,149.0,198998.0,4,0,234,12994,285,418624,1
1,80,1,3,1.871487,151.0,198966.0,4,0,282,15702,282,412612,1
2,80,1,3,2.376374,148.0,140547.0,4,0,174,9600,201,291562,1
3,80,1,0,3.092539,0.0,0.0,0,0,6,360,0,0,0
4,80,1,3,1.359780,148.0,137299.0,4,0,178,9840,196,284806,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5410556,8081,1,0,NaN,NaN,NaN,0,0,1,40,0,0,1
5410557,4554,1,0,26347.422164,11.0,4413.0,1,0,1796,93758,1792,102154,1
5410558,4554,1,0,0.304830,11.0,11.0,4,0,10,558,8,430,1
5410559,13,0,0,0.000005,56.0,0.0,12,0,2,112,0,0,0
5410560,0,0,0,0.000005,56.0,0.0,12,0,2,112,0,0,0

In [29]:
df['Label'].value_counts()

Label
1    5406896
0       3665
Name: count, dtype: int64

In [30]:
df['Label'] = df['Label'].dropna()

In [31]:
df.drop(df.index[df['Label'] == 'nan'], inplace = True)

In [32]:
df

,id.resp_p,proto,service,duration,orig_bytes,resp_bytes,conn_state,missed_bytes,orig_pkts,orig_ip_bytes,resp_pkts,resp_ip_bytes,Label
0,80,1,3,1.874424,149.0,198998.0,4,0,234,12994,285,418624,1
1,80,1,3,1.871487,151.0,198966.0,4,0,282,15702,282,412612,1
2,80,1,3,2.376374,148.0,140547.0,4,0,174,9600,201,291562,1
3,80,1,0,3.092539,0.0,0.0,0,0,6,360,0,0,0
4,80,1,3,1.359780,148.0,137299.0,4,0,178,9840,196,284806,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5410556,8081,1,0,NaN,NaN,NaN,0,0,1,40,0,0,1
5410557,4554,1,0,26347.422164,11.0,4413.0,1,0,1796,93758,1792,102154,1
5410558,4554,1,0,0.304830,11.0,11.0,4,0,10,558,8,430,1
5410559,13,0,0,0.000005,56.0,0.0,12,0,2,112,0,0,0
5410560,0,0,0,0.000005,56.0,0.0,12,0,2,112,0,0,0

In [33]:
import pandas as pd
import numpy as np

# Assuming df is your loaded DataFrame

# Calculate medians for non-S0 connections
non_s0_mask = df['conn_state'] != 0
medians = {
    'duration': df.loc[non_s0_mask, 'duration'].median(),
    'orig_bytes': df.loc[non_s0_mask, 'orig_bytes'].median(),
    'resp_bytes': df.loc[non_s0_mask, 'resp_bytes'].median()
}

# Only fill NaN values where conn_state == 0
for col in ['duration', 'orig_bytes', 'resp_bytes']:
    # For conn_state == 0: Fill ONLY NaNs with 0
    df.loc[(df['conn_state'] == 0) & (df[col].isna()), col] = 0
    
    # For conn_state != 0: Fill NaNs with their respective medians
    df.loc[(df['conn_state'] != 0) & (df[col].isna()), col] = medians[col]

# Verify the results
print("NaN values after imputation:")
print(df[['duration', 'orig_bytes', 'resp_bytes']].isna().sum())

NaN values after imputation:
duration      0
orig_bytes    0
resp_bytes    0
dtype: int64

In [34]:
df['Label'].isnull().values.any()

False

In [35]:
df

,id.resp_p,proto,service,duration,orig_bytes,resp_bytes,conn_state,missed_bytes,orig_pkts,orig_ip_bytes,resp_pkts,resp_ip_bytes,Label
0,80,1,3,1.874424,149.0,198998.0,4,0,234,12994,285,418624,1
1,80,1,3,1.871487,151.0,198966.0,4,0,282,15702,282,412612,1
2,80,1,3,2.376374,148.0,140547.0,4,0,174,9600,201,291562,1
3,80,1,0,3.092539,0.0,0.0,0,0,6,360,0,0,0
4,80,1,3,1.359780,148.0,137299.0,4,0,178,9840,196,284806,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5410556,8081,1,0,0.000000,0.0,0.0,0,0,1,40,0,0,1
5410557,4554,1,0,26347.422164,11.0,4413.0,1,0,1796,93758,1792,102154,1
5410558,4554,1,0,0.304830,11.0,11.0,4,0,10,558,8,430,1
5410559,13,0,0,0.000005,56.0,0.0,12,0,2,112,0,0,0
5410560,0,0,0,0.000005,56.0,0.0,12,0,2,112,0,0,0

In [36]:
import pandas as pd

# Check for NaN values in the current DataFrame
nan_check = df.isna().sum()

# Filter to only show columns with NaN values
nan_columns = nan_check[nan_check > 0]

if nan_columns.empty:
    print("No NaN values found in the DataFrame")
else:
    print("Columns with NaN values and their counts:")
    for col, count in nan_columns.items():
        print(f"- {col}: {count} NaN values")
    
    print(f"\nTotal NaN values in DataFrame: {nan_check.sum()}")

No NaN values found in the DataFrame

In [37]:
df['missed_bytes'] = df['missed_bytes'].fillna(0)

In [38]:
df.to_csv(r"49cleaned.csv",index=False)