In [1]:
import pandas as pd
import numpy as np
df = pd.read_csv(r"34.csv")

In [2]:
df

,Unnamed: 0,ts,uid,id.orig_h,id.orig_p,id.resp_h,id.resp_p,proto,service,duration,...,conn_state,local_orig,local_resp,missed_bytes,history,orig_pkts,orig_ip_bytes,resp_pkts,resp_ip_bytes,tunnel_parents label detailed-label
0,0,1.545404e+09,CrDn63WjJEmrWGjqf,192.168.1.195,41040,185.244.25.235,80,tcp,-,3.139211,...,S0,-,-,0,S,3,180,0,0,- Benign -
1,1,1.545404e+09,CY9lJW3gh1Eje4usP6,192.168.1.195,41040,185.244.25.235,80,tcp,-,-,...,S0,-,-,0,S,1,60,0,0,- Benign -
2,2,1.545404e+09,CcFXLynukEDnUlvgl,192.168.1.195,41040,185.244.25.235,80,tcp,-,-,...,S0,-,-,0,S,1,60,0,0,- Benign -
3,3,1.545404e+09,CDrkrSobGYxHhYfth,192.168.1.195,41040,185.244.25.235,80,tcp,http,1.477656,...,SF,-,-,2896,ShADadttcfF,94,5525,96,139044,- Benign -
4,4,1.545404e+09,CTWZQf2oJSvq6zmPAc,192.168.1.195,41042,185.244.25.235,80,tcp,-,3.147116,...,S0,-,-,0,S,3,180,0,0,- Benign -
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23140,23140,1.545490e+09,C2F17zSUnGOcWzBa7,192.168.1.195,57110,185.244.25.235,6667,tcp,irc,32.840994,...,S3,-,-,0,ShAdDaf,7,434,6,589,- Malicious C&C
23141,23141,1.545490e+09,C93P4z4k5IRJD1rXJg,192.168.1.195,57092,185.244.25.235,6667,tcp,irc,36.290833,...,S3,-,-,0,ShAdDaf,10,606,7,632,- Malicious C&C
23142,23142,1.545490e+09,CXLZ3A2QY5E8weqpDk,192.168.1.195,123,147.251.48.140,123,udp,-,-,...,S0,-,-,0,D,1,76,0,0,- Benign -
23143,23143,1.545490e+09,CuXpFN3fWesWBXUhq1,192.168.1.195,123,82.113.53.40,123,udp,-,-,...,S0,-,-,0,D,1,76,0,0,- Benign -
23144,23144,1.545490e+09,Ct2Yhy4d33oL3yyZY9,192.168.1.195,123,89.221.210.188,123,udp,-,-,...,S0,-,-,0,D,1,76,0,0,- Benign -

In [3]:
df = df.rename(columns={"tunnel_parents   label   detailed-label": "Label"})
df.drop(df.index[df['Label'] == 'nan'], inplace = True)

In [4]:
df['Label']=df['Label'].replace('   benign   ','benign')
df['Label']=df['Label'].replace('(empty)   Benign   -','benign')
df['Label']=df['Label'].replace('-   Benign   -','benign')
df['Label']=df['Label'].replace('-   benign   -','benign')
df['Label']=df['Label'].replace('(empty)   benign   -','benign')

In [5]:
df["Label"].value_counts()

Label
-   Malicious   DDoS                         14394
-   Malicious   C&C                           6706
benign                                        1923
-   Malicious   PartOfAHorizontalPortScan      122
Name: count, dtype: int64

In [6]:
# Transform Label column
df['Label'] = np.where(df['Label'] == 'benign', 0, 1)

In [7]:
df["Label"].value_counts()

Label
1    21222
0     1923
Name: count, dtype: int64

In [8]:
df

,Unnamed: 0,ts,uid,id.orig_h,id.orig_p,id.resp_h,id.resp_p,proto,service,duration,...,conn_state,local_orig,local_resp,missed_bytes,history,orig_pkts,orig_ip_bytes,resp_pkts,resp_ip_bytes,Label
0,0,1.545404e+09,CrDn63WjJEmrWGjqf,192.168.1.195,41040,185.244.25.235,80,tcp,-,3.139211,...,S0,-,-,0,S,3,180,0,0,0
1,1,1.545404e+09,CY9lJW3gh1Eje4usP6,192.168.1.195,41040,185.244.25.235,80,tcp,-,-,...,S0,-,-,0,S,1,60,0,0,0
2,2,1.545404e+09,CcFXLynukEDnUlvgl,192.168.1.195,41040,185.244.25.235,80,tcp,-,-,...,S0,-,-,0,S,1,60,0,0,0
3,3,1.545404e+09,CDrkrSobGYxHhYfth,192.168.1.195,41040,185.244.25.235,80,tcp,http,1.477656,...,SF,-,-,2896,ShADadttcfF,94,5525,96,139044,0
4,4,1.545404e+09,CTWZQf2oJSvq6zmPAc,192.168.1.195,41042,185.244.25.235,80,tcp,-,3.147116,...,S0,-,-,0,S,3,180,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23140,23140,1.545490e+09,C2F17zSUnGOcWzBa7,192.168.1.195,57110,185.244.25.235,6667,tcp,irc,32.840994,...,S3,-,-,0,ShAdDaf,7,434,6,589,1
23141,23141,1.545490e+09,C93P4z4k5IRJD1rXJg,192.168.1.195,57092,185.244.25.235,6667,tcp,irc,36.290833,...,S3,-,-,0,ShAdDaf,10,606,7,632,1
23142,23142,1.545490e+09,CXLZ3A2QY5E8weqpDk,192.168.1.195,123,147.251.48.140,123,udp,-,-,...,S0,-,-,0,D,1,76,0,0,0
23143,23143,1.545490e+09,CuXpFN3fWesWBXUhq1,192.168.1.195,123,82.113.53.40,123,udp,-,-,...,S0,-,-,0,D,1,76,0,0,0
23144,23144,1.545490e+09,Ct2Yhy4d33oL3yyZY9,192.168.1.195,123,89.221.210.188,123,udp,-,-,...,S0,-,-,0,D,1,76,0,0,0

In [9]:
#Encodeing Features
import pandas as pd

# Your predefined encoding dictionary
encoding_map = {
    "proto": {
        "icmp": 0,
        "tcp": 1,
        "udp": 2,
        "UNKNOWN": -1
    },
    "service": {
        "-": 0,
        "dhcp": 1,
        "dns": 2,
        "http": 3,
        "ssh": 4,
        "ssl": 5,
        "irc": 6,
        "UNKNOWN": -1
    },
    "conn_state": {
         "S0": 0,
         "S1": 1,
         "S2": 2,
         "S3": 3,
         "SF": 4,
         "REJ": 5,
         "RSTO": 6,
         "RSTR": 7,
         "RSTOS0": 8,
         "RSTRH": 9,
         "SH": 10,
         "SHR": 11,
         "OTH": 12,
         "UNKNOWN": -1
    }
}

def encode_categorical(df, encoding_map):
    """
    Convert categorical columns in DataFrame to numerical values using the encoding map.
    Unknown values will be mapped to -1.
    """
    for col in encoding_map:
        if col in df.columns:
            df[col] = df[col].map(encoding_map[col]).fillna(-1).astype(int)
    return df

In [10]:

df= encode_categorical(df, encoding_map)

In [11]:
df

,Unnamed: 0,ts,uid,id.orig_h,id.orig_p,id.resp_h,id.resp_p,proto,service,duration,...,conn_state,local_orig,local_resp,missed_bytes,history,orig_pkts,orig_ip_bytes,resp_pkts,resp_ip_bytes,Label
0,0,1.545404e+09,CrDn63WjJEmrWGjqf,192.168.1.195,41040,185.244.25.235,80,1,0,3.139211,...,0,-,-,0,S,3,180,0,0,0
1,1,1.545404e+09,CY9lJW3gh1Eje4usP6,192.168.1.195,41040,185.244.25.235,80,1,0,-,...,0,-,-,0,S,1,60,0,0,0
2,2,1.545404e+09,CcFXLynukEDnUlvgl,192.168.1.195,41040,185.244.25.235,80,1,0,-,...,0,-,-,0,S,1,60,0,0,0
3,3,1.545404e+09,CDrkrSobGYxHhYfth,192.168.1.195,41040,185.244.25.235,80,1,3,1.477656,...,4,-,-,2896,ShADadttcfF,94,5525,96,139044,0
4,4,1.545404e+09,CTWZQf2oJSvq6zmPAc,192.168.1.195,41042,185.244.25.235,80,1,0,3.147116,...,0,-,-,0,S,3,180,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23140,23140,1.545490e+09,C2F17zSUnGOcWzBa7,192.168.1.195,57110,185.244.25.235,6667,1,6,32.840994,...,3,-,-,0,ShAdDaf,7,434,6,589,1
23141,23141,1.545490e+09,C93P4z4k5IRJD1rXJg,192.168.1.195,57092,185.244.25.235,6667,1,6,36.290833,...,3,-,-,0,ShAdDaf,10,606,7,632,1
23142,23142,1.545490e+09,CXLZ3A2QY5E8weqpDk,192.168.1.195,123,147.251.48.140,123,2,0,-,...,0,-,-,0,D,1,76,0,0,0
23143,23143,1.545490e+09,CuXpFN3fWesWBXUhq1,192.168.1.195,123,82.113.53.40,123,2,0,-,...,0,-,-,0,D,1,76,0,0,0
23144,23144,1.545490e+09,Ct2Yhy4d33oL3yyZY9,192.168.1.195,123,89.221.210.188,123,2,0,-,...,0,-,-,0,D,1,76,0,0,0

In [12]:
import pandas as pd
import numpy as np
from scipy.stats import pointbiserialr, chi2_contingency
from sklearn.feature_selection import mutual_info_classif

# Check dtypes
print("Data Types:\n", df.dtypes)

Data Types:
 Unnamed: 0         int64
ts               float64
uid               object
id.orig_h         object
id.orig_p          int64
id.resp_h         object
id.resp_p          int64
proto              int32
service            int32
duration          object
orig_bytes        object
resp_bytes        object
conn_state         int32
local_orig        object
local_resp        object
missed_bytes       int64
history           object
orig_pkts          int64
orig_ip_bytes      int64
resp_pkts          int64
resp_ip_bytes      int64
Label              int32
dtype: object

In [13]:
df = df.drop('Unnamed: 0', axis=1)  
df = df.drop('ts', axis=1)  
df = df.drop('uid', axis=1)  
df = df.drop('local_orig', axis=1)  
df = df.drop('local_resp', axis=1)  
df = df.drop('id.orig_h', axis=1)  
df = df.drop('id.resp_h', axis=1)  
df = df.drop('id.orig_p', axis=1)  
df = df.drop('history', axis=1)

In [14]:
df.dtypes

id.resp_p         int64
proto             int32
service           int32
duration         object
orig_bytes       object
resp_bytes       object
conn_state        int32
missed_bytes      int64
orig_pkts         int64
orig_ip_bytes     int64
resp_pkts         int64
resp_ip_bytes     int64
Label             int32
dtype: object

In [15]:
# Convert "numeric-as-object" columns to float/int
cols_to_convert = ['duration', 'orig_bytes', 'resp_bytes']
df[cols_to_convert] = df[cols_to_convert].apply(pd.to_numeric, errors='coerce')  # 'coerce' sets invalid parsing as NaN

In [16]:
df.dtypes

id.resp_p          int64
proto              int32
service            int32
duration         float64
orig_bytes       float64
resp_bytes       float64
conn_state         int32
missed_bytes       int64
orig_pkts          int64
orig_ip_bytes      int64
resp_pkts          int64
resp_ip_bytes      int64
Label              int32
dtype: object

In [17]:
df

,id.resp_p,proto,service,duration,orig_bytes,resp_bytes,conn_state,missed_bytes,orig_pkts,orig_ip_bytes,resp_pkts,resp_ip_bytes,Label
0,80,1,0,3.139211,0.0,0.0,0,0,3,180,0,0,0
1,80,1,0,NaN,NaN,NaN,0,0,1,60,0,0,0
2,80,1,0,NaN,NaN,NaN,0,0,1,60,0,0,0
3,80,1,3,1.477656,149.0,128252.0,4,2896,94,5525,96,139044,0
4,80,1,0,3.147116,0.0,0.0,0,0,3,180,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
23140,6667,1,6,32.840994,62.0,269.0,3,0,7,434,6,589,1
23141,6667,1,6,36.290833,62.0,260.0,3,0,10,606,7,632,1
23142,123,2,0,NaN,NaN,NaN,0,0,1,76,0,0,0
23143,123,2,0,NaN,NaN,NaN,0,0,1,76,0,0,0
23144,123,2,0,NaN,NaN,NaN,0,0,1,76,0,0,0

In [18]:
print(df.dtypes)

id.resp_p          int64
proto              int32
service            int32
duration         float64
orig_bytes       float64
resp_bytes       float64
conn_state         int32
missed_bytes       int64
orig_pkts          int64
orig_ip_bytes      int64
resp_pkts          int64
resp_ip_bytes      int64
Label              int32
dtype: object

In [19]:
print(df[['id.resp_p', 'missed_bytes', 'orig_pkts']].describe())

          id.resp_p  missed_bytes     orig_pkts
count  23145.000000  23145.000000  23145.000000
mean    2324.573558      2.127112      6.375157
std     5362.933817    102.490787    178.548725
min        1.000000      0.000000      0.000000
25%       80.000000      0.000000      0.000000
50%       80.000000      0.000000      0.000000
75%     6667.000000      0.000000      1.000000
max    63798.000000   5792.000000  18444.000000

In [20]:
df["Label"].value_counts()

Label
1    21222
0     1923
Name: count, dtype: int64

In [21]:
df

,id.resp_p,proto,service,duration,orig_bytes,resp_bytes,conn_state,missed_bytes,orig_pkts,orig_ip_bytes,resp_pkts,resp_ip_bytes,Label
0,80,1,0,3.139211,0.0,0.0,0,0,3,180,0,0,0
1,80,1,0,NaN,NaN,NaN,0,0,1,60,0,0,0
2,80,1,0,NaN,NaN,NaN,0,0,1,60,0,0,0
3,80,1,3,1.477656,149.0,128252.0,4,2896,94,5525,96,139044,0
4,80,1,0,3.147116,0.0,0.0,0,0,3,180,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
23140,6667,1,6,32.840994,62.0,269.0,3,0,7,434,6,589,1
23141,6667,1,6,36.290833,62.0,260.0,3,0,10,606,7,632,1
23142,123,2,0,NaN,NaN,NaN,0,0,1,76,0,0,0
23143,123,2,0,NaN,NaN,NaN,0,0,1,76,0,0,0
23144,123,2,0,NaN,NaN,NaN,0,0,1,76,0,0,0

In [22]:
df['Label'].value_counts()

Label
1    21222
0     1923
Name: count, dtype: int64

In [23]:
df['Label'] = df['Label'].dropna()

In [24]:
df.drop(df.index[df['Label'] == 'nan'], inplace = True)

In [25]:
df

,id.resp_p,proto,service,duration,orig_bytes,resp_bytes,conn_state,missed_bytes,orig_pkts,orig_ip_bytes,resp_pkts,resp_ip_bytes,Label
0,80,1,0,3.139211,0.0,0.0,0,0,3,180,0,0,0
1,80,1,0,NaN,NaN,NaN,0,0,1,60,0,0,0
2,80,1,0,NaN,NaN,NaN,0,0,1,60,0,0,0
3,80,1,3,1.477656,149.0,128252.0,4,2896,94,5525,96,139044,0
4,80,1,0,3.147116,0.0,0.0,0,0,3,180,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
23140,6667,1,6,32.840994,62.0,269.0,3,0,7,434,6,589,1
23141,6667,1,6,36.290833,62.0,260.0,3,0,10,606,7,632,1
23142,123,2,0,NaN,NaN,NaN,0,0,1,76,0,0,0
23143,123,2,0,NaN,NaN,NaN,0,0,1,76,0,0,0
23144,123,2,0,NaN,NaN,NaN,0,0,1,76,0,0,0

In [26]:
import pandas as pd
import numpy as np

# Assuming df is your loaded DataFrame

# Calculate medians for non-S0 connections
non_s0_mask = df['conn_state'] != 0
medians = {
    'duration': df.loc[non_s0_mask, 'duration'].median(),
    'orig_bytes': df.loc[non_s0_mask, 'orig_bytes'].median(),
    'resp_bytes': df.loc[non_s0_mask, 'resp_bytes'].median()
}

# Only fill NaN values where conn_state == 0
for col in ['duration', 'orig_bytes', 'resp_bytes']:
    # For conn_state == 0: Fill ONLY NaNs with 0
    df.loc[(df['conn_state'] == 0) & (df[col].isna()), col] = 0
    
    # For conn_state != 0: Fill NaNs with their respective medians
    df.loc[(df['conn_state'] != 0) & (df[col].isna()), col] = medians[col]

# Verify the results
print("NaN values after imputation:")
print(df[['duration', 'orig_bytes', 'resp_bytes']].isna().sum())

NaN values after imputation:
duration      0
orig_bytes    0
resp_bytes    0
dtype: int64

In [27]:
df['Label'].isnull().values.any()

False

In [28]:
df

,id.resp_p,proto,service,duration,orig_bytes,resp_bytes,conn_state,missed_bytes,orig_pkts,orig_ip_bytes,resp_pkts,resp_ip_bytes,Label
0,80,1,0,3.139211,0.0,0.0,0,0,3,180,0,0,0
1,80,1,0,0.000000,0.0,0.0,0,0,1,60,0,0,0
2,80,1,0,0.000000,0.0,0.0,0,0,1,60,0,0,0
3,80,1,3,1.477656,149.0,128252.0,4,2896,94,5525,96,139044,0
4,80,1,0,3.147116,0.0,0.0,0,0,3,180,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
23140,6667,1,6,32.840994,62.0,269.0,3,0,7,434,6,589,1
23141,6667,1,6,36.290833,62.0,260.0,3,0,10,606,7,632,1
23142,123,2,0,0.000000,0.0,0.0,0,0,1,76,0,0,0
23143,123,2,0,0.000000,0.0,0.0,0,0,1,76,0,0,0
23144,123,2,0,0.000000,0.0,0.0,0,0,1,76,0,0,0

In [29]:
import pandas as pd

# Check for NaN values in the current DataFrame
nan_check = df.isna().sum()

# Filter to only show columns with NaN values
nan_columns = nan_check[nan_check > 0]

if nan_columns.empty:
    print("No NaN values found in the DataFrame")
else:
    print("Columns with NaN values and their counts:")
    for col, count in nan_columns.items():
        print(f"- {col}: {count} NaN values")
    
    print(f"\nTotal NaN values in DataFrame: {nan_check.sum()}")

No NaN values found in the DataFrame

In [30]:
df['missed_bytes'] = df['missed_bytes'].fillna(0)

In [31]:
df.to_csv(r"34cleaned.csv",index=False)