In [1]:
import pandas as pd
import numpy as np
df = pd.read_csv(r"7.csv")

In [2]:
df

,Unnamed: 0,ts,uid,id.orig_h,id.orig_p,id.resp_h,id.resp_p,proto,service,duration,...,conn_state,local_orig,local_resp,missed_bytes,history,orig_pkts,orig_ip_bytes,resp_pkts,resp_ip_bytes,tunnel_parents label detailed-label
0,0,1.537523e+09,CJAF5z3MDFg4XVDXB,0.0.0.0,68,255.255.255.255,67,udp,dhcp,8.322388,...,S0,-,-,0,D,2,656,0,0,- benign -
1,1,1.537523e+09,CcYEFX3Qj9xdNX1ZCa,192.168.2.1,5353,224.0.0.251,5353,udp,dns,-,...,S0,-,-,0,D,1,391,0,0,- benign -
2,2,1.537523e+09,CF6fCK1nFqvI1XxGM1,fe80::80e6:50ff:fe12:1464,5353,ff02::fb,5353,udp,dns,-,...,S0,-,-,0,D,1,411,0,0,- benign -
3,3,1.537523e+09,C2dlio3MkdwWJ80y04,169.254.15.115,5353,224.0.0.251,5353,udp,dns,-,...,S0,-,-,0,D,1,391,0,0,- benign -
4,4,1.537523e+09,COrF0t2uLErai9nfH5,0.0.0.0,68,255.255.255.255,67,udp,dhcp,60.555587,...,S0,-,-,0,D,10,3280,0,0,- benign -
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1369,1369,1.537543e+09,CrPQ4n1jVFxbm0mcj9,192.168.69.136,51443,239.255.255.250,1900,udp,-,-,...,S0,-,-,0,D,1,153,0,0,- benign -
1370,1370,1.537543e+09,Ce0LkH33VlZBF8Vw93,fe80::106c:9e5b:3af8:9cf,143,ff02::16,0,icmp,-,1.945701,...,OTH,-,-,0,-,2,152,0,0,- benign -
1371,1371,1.537543e+09,CdWSpn4EA2vXfUBqI7,fe80::183b:7564:dbcc:3eca,143,ff02::16,0,icmp,-,1.024087,...,OTH,-,-,0,-,2,152,0,0,- benign -
1372,1372,1.537543e+09,ClKCqX3JOxjrti9lLh,fe80::1847:a1bd:8d13:f43c,143,ff02::16,0,icmp,-,59.390351,...,OTH,-,-,0,-,4,304,0,0,- benign -
1373,1373,1.537543e+09,CDsdf81FPzUzFBBRBe,fe80::1c5c:213d:7cf8:890,143,ff02::16,0,icmp,-,-,...,OTH,-,-,0,-,1,76,0,0,- benign -

In [3]:
df = df.rename(columns={"tunnel_parents   label   detailed-label": "Label"})
df.drop(df.index[df['Label'] == 'nan'], inplace = True)

In [4]:
df['Label']=df['Label'].replace('   benign   ','benign')
df['Label']=df['Label'].replace('(empty)   Benign   -','benign')
df['Label']=df['Label'].replace('-   Benign   -','benign')
df['Label']=df['Label'].replace('-   benign   -','benign')
df['Label']=df['Label'].replace('(empty)   benign   -','benign')

In [5]:
df["Label"].value_counts()

Label
benign    1374
Name: count, dtype: int64

In [6]:
# Transform Label column
df['Label'] = np.where(df['Label'] == 'benign', 0, 1)

In [7]:
df["Label"].value_counts()

Label
0    1374
Name: count, dtype: int64

In [8]:
df

,Unnamed: 0,ts,uid,id.orig_h,id.orig_p,id.resp_h,id.resp_p,proto,service,duration,...,conn_state,local_orig,local_resp,missed_bytes,history,orig_pkts,orig_ip_bytes,resp_pkts,resp_ip_bytes,Label
0,0,1.537523e+09,CJAF5z3MDFg4XVDXB,0.0.0.0,68,255.255.255.255,67,udp,dhcp,8.322388,...,S0,-,-,0,D,2,656,0,0,0
1,1,1.537523e+09,CcYEFX3Qj9xdNX1ZCa,192.168.2.1,5353,224.0.0.251,5353,udp,dns,-,...,S0,-,-,0,D,1,391,0,0,0
2,2,1.537523e+09,CF6fCK1nFqvI1XxGM1,fe80::80e6:50ff:fe12:1464,5353,ff02::fb,5353,udp,dns,-,...,S0,-,-,0,D,1,411,0,0,0
3,3,1.537523e+09,C2dlio3MkdwWJ80y04,169.254.15.115,5353,224.0.0.251,5353,udp,dns,-,...,S0,-,-,0,D,1,391,0,0,0
4,4,1.537523e+09,COrF0t2uLErai9nfH5,0.0.0.0,68,255.255.255.255,67,udp,dhcp,60.555587,...,S0,-,-,0,D,10,3280,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1369,1369,1.537543e+09,CrPQ4n1jVFxbm0mcj9,192.168.69.136,51443,239.255.255.250,1900,udp,-,-,...,S0,-,-,0,D,1,153,0,0,0
1370,1370,1.537543e+09,Ce0LkH33VlZBF8Vw93,fe80::106c:9e5b:3af8:9cf,143,ff02::16,0,icmp,-,1.945701,...,OTH,-,-,0,-,2,152,0,0,0
1371,1371,1.537543e+09,CdWSpn4EA2vXfUBqI7,fe80::183b:7564:dbcc:3eca,143,ff02::16,0,icmp,-,1.024087,...,OTH,-,-,0,-,2,152,0,0,0
1372,1372,1.537543e+09,ClKCqX3JOxjrti9lLh,fe80::1847:a1bd:8d13:f43c,143,ff02::16,0,icmp,-,59.390351,...,OTH,-,-,0,-,4,304,0,0,0
1373,1373,1.537543e+09,CDsdf81FPzUzFBBRBe,fe80::1c5c:213d:7cf8:890,143,ff02::16,0,icmp,-,-,...,OTH,-,-,0,-,1,76,0,0,0

In [9]:
#Encodeing Features
import pandas as pd

# Your predefined encoding dictionary
encoding_map = {
    "proto": {
        "icmp": 0,
        "tcp": 1,
        "udp": 2,
        "UNKNOWN": -1
    },
    "service": {
        "-": 0,
        "dhcp": 1,
        "dns": 2,
        "http": 3,
        "ssh": 4,
        "ssl": 5,
        "irc": 6,
        "UNKNOWN": -1
    },
    "conn_state": {
         "S0": 0,
         "S1": 1,
         "S2": 2,
         "S3": 3,
         "SF": 4,
         "REJ": 5,
         "RSTO": 6,
         "RSTR": 7,
         "RSTOS0": 8,
         "RSTRH": 9,
         "SH": 10,
         "SHR": 11,
         "OTH": 12,
         "UNKNOWN": -1
    }
}

def encode_categorical(df, encoding_map):
    """
    Convert categorical columns in DataFrame to numerical values using the encoding map.
    Unknown values will be mapped to -1.
    """
    for col in encoding_map:
        if col in df.columns:
            df[col] = df[col].map(encoding_map[col]).fillna(-1).astype(int)
    return df

In [10]:

df= encode_categorical(df, encoding_map)

In [12]:
df

,Unnamed: 0,ts,uid,id.orig_h,id.orig_p,id.resp_h,id.resp_p,proto,service,duration,...,conn_state,local_orig,local_resp,missed_bytes,history,orig_pkts,orig_ip_bytes,resp_pkts,resp_ip_bytes,Label
0,0,1.537523e+09,CJAF5z3MDFg4XVDXB,0.0.0.0,68,255.255.255.255,67,2,1,8.322388,...,0,-,-,0,D,2,656,0,0,0
1,1,1.537523e+09,CcYEFX3Qj9xdNX1ZCa,192.168.2.1,5353,224.0.0.251,5353,2,2,-,...,0,-,-,0,D,1,391,0,0,0
2,2,1.537523e+09,CF6fCK1nFqvI1XxGM1,fe80::80e6:50ff:fe12:1464,5353,ff02::fb,5353,2,2,-,...,0,-,-,0,D,1,411,0,0,0
3,3,1.537523e+09,C2dlio3MkdwWJ80y04,169.254.15.115,5353,224.0.0.251,5353,2,2,-,...,0,-,-,0,D,1,391,0,0,0
4,4,1.537523e+09,COrF0t2uLErai9nfH5,0.0.0.0,68,255.255.255.255,67,2,1,60.555587,...,0,-,-,0,D,10,3280,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1369,1369,1.537543e+09,CrPQ4n1jVFxbm0mcj9,192.168.69.136,51443,239.255.255.250,1900,2,0,-,...,0,-,-,0,D,1,153,0,0,0
1370,1370,1.537543e+09,Ce0LkH33VlZBF8Vw93,fe80::106c:9e5b:3af8:9cf,143,ff02::16,0,0,0,1.945701,...,12,-,-,0,-,2,152,0,0,0
1371,1371,1.537543e+09,CdWSpn4EA2vXfUBqI7,fe80::183b:7564:dbcc:3eca,143,ff02::16,0,0,0,1.024087,...,12,-,-,0,-,2,152,0,0,0
1372,1372,1.537543e+09,ClKCqX3JOxjrti9lLh,fe80::1847:a1bd:8d13:f43c,143,ff02::16,0,0,0,59.390351,...,12,-,-,0,-,4,304,0,0,0
1373,1373,1.537543e+09,CDsdf81FPzUzFBBRBe,fe80::1c5c:213d:7cf8:890,143,ff02::16,0,0,0,-,...,12,-,-,0,-,1,76,0,0,0

In [13]:
import pandas as pd
import numpy as np
from scipy.stats import pointbiserialr, chi2_contingency
from sklearn.feature_selection import mutual_info_classif

# Check dtypes
print("Data Types:\n", df.dtypes)

Data Types:
 Unnamed: 0         int64
ts               float64
uid               object
id.orig_h         object
id.orig_p          int64
id.resp_h         object
id.resp_p          int64
proto              int32
service            int32
duration          object
orig_bytes        object
resp_bytes        object
conn_state         int32
local_orig        object
local_resp        object
missed_bytes       int64
history           object
orig_pkts          int64
orig_ip_bytes      int64
resp_pkts          int64
resp_ip_bytes      int64
Label              int32
dtype: object

In [14]:
df = df.drop('Unnamed: 0', axis=1)  
df = df.drop('ts', axis=1)  
df = df.drop('uid', axis=1)  
df = df.drop('local_orig', axis=1)  
df = df.drop('local_resp', axis=1)  
df = df.drop('id.orig_h', axis=1)  
df = df.drop('id.resp_h', axis=1)  
df = df.drop('id.orig_p', axis=1)  
df = df.drop('history', axis=1)

In [15]:
df.dtypes

id.resp_p         int64
proto             int32
service           int32
duration         object
orig_bytes       object
resp_bytes       object
conn_state        int32
missed_bytes      int64
orig_pkts         int64
orig_ip_bytes     int64
resp_pkts         int64
resp_ip_bytes     int64
Label             int32
dtype: object

In [16]:
# Convert "numeric-as-object" columns to float/int
cols_to_convert = ['duration', 'orig_bytes', 'resp_bytes']
df[cols_to_convert] = df[cols_to_convert].apply(pd.to_numeric, errors='coerce')  # 'coerce' sets invalid parsing as NaN

In [17]:
df.dtypes

id.resp_p          int64
proto              int32
service            int32
duration         float64
orig_bytes       float64
resp_bytes       float64
conn_state         int32
missed_bytes       int64
orig_pkts          int64
orig_ip_bytes      int64
resp_pkts          int64
resp_ip_bytes      int64
Label              int32
dtype: object

In [19]:
print(df.dtypes)

id.resp_p          int64
proto              int32
service            int32
duration         float64
orig_bytes       float64
resp_bytes       float64
conn_state         int32
missed_bytes       int64
orig_pkts          int64
orig_ip_bytes      int64
resp_pkts          int64
resp_ip_bytes      int64
Label              int32
dtype: object

In [20]:
df

,id.resp_p,proto,service,duration,orig_bytes,resp_bytes,conn_state,missed_bytes,orig_pkts,orig_ip_bytes,resp_pkts,resp_ip_bytes,Label
0,67,2,1,8.322388,600.0,0.0,0,0,2,656,0,0,0
1,5353,2,2,NaN,NaN,NaN,0,0,1,391,0,0,0
2,5353,2,2,NaN,NaN,NaN,0,0,1,411,0,0,0
3,5353,2,2,NaN,NaN,NaN,0,0,1,391,0,0,0
4,67,2,1,60.555587,3000.0,0.0,0,0,10,3280,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1369,1900,2,0,NaN,NaN,NaN,0,0,1,153,0,0,0
1370,0,0,0,1.945701,40.0,0.0,12,0,2,152,0,0,0
1371,0,0,0,1.024087,40.0,0.0,12,0,2,152,0,0,0
1372,0,0,0,59.390351,80.0,0.0,12,0,4,304,0,0,0
1373,0,0,0,NaN,NaN,NaN,12,0,1,76,0,0,0

In [21]:
print(df.dtypes)

id.resp_p          int64
proto              int32
service            int32
duration         float64
orig_bytes       float64
resp_bytes       float64
conn_state         int32
missed_bytes       int64
orig_pkts          int64
orig_ip_bytes      int64
resp_pkts          int64
resp_ip_bytes      int64
Label              int32
dtype: object

In [22]:
print(df[['id.resp_p', 'missed_bytes', 'orig_pkts']].describe())

          id.resp_p  missed_bytes      orig_pkts
count   1374.000000        1374.0    1374.000000
mean    1073.914119           0.0     103.873362
std     3270.789519           0.0    3343.205784
min        0.000000           0.0       0.000000
25%       53.000000           0.0       1.000000
50%       80.000000           0.0       2.000000
75%      443.000000           0.0       9.000000
max    57621.000000           0.0  123657.000000

In [23]:
df["Label"].value_counts()

Label
0    1374
Name: count, dtype: int64

In [24]:
df

,id.resp_p,proto,service,duration,orig_bytes,resp_bytes,conn_state,missed_bytes,orig_pkts,orig_ip_bytes,resp_pkts,resp_ip_bytes,Label
0,67,2,1,8.322388,600.0,0.0,0,0,2,656,0,0,0
1,5353,2,2,NaN,NaN,NaN,0,0,1,391,0,0,0
2,5353,2,2,NaN,NaN,NaN,0,0,1,411,0,0,0
3,5353,2,2,NaN,NaN,NaN,0,0,1,391,0,0,0
4,67,2,1,60.555587,3000.0,0.0,0,0,10,3280,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1369,1900,2,0,NaN,NaN,NaN,0,0,1,153,0,0,0
1370,0,0,0,1.945701,40.0,0.0,12,0,2,152,0,0,0
1371,0,0,0,1.024087,40.0,0.0,12,0,2,152,0,0,0
1372,0,0,0,59.390351,80.0,0.0,12,0,4,304,0,0,0
1373,0,0,0,NaN,NaN,NaN,12,0,1,76,0,0,0

In [29]:
df['Label'].value_counts()

Label
0    1374
Name: count, dtype: int64

In [30]:
df['Label'] = df['Label'].dropna()

In [31]:
df.drop(df.index[df['Label'] == 'nan'], inplace = True)

In [32]:
df

,id.resp_p,proto,service,duration,orig_bytes,resp_bytes,conn_state,missed_bytes,orig_pkts,orig_ip_bytes,resp_pkts,resp_ip_bytes,Label
0,67,2,1,8.322388,600.0,0.0,0,0,2,656,0,0,0
1,5353,2,2,NaN,NaN,NaN,0,0,1,391,0,0,0
2,5353,2,2,NaN,NaN,NaN,0,0,1,411,0,0,0
3,5353,2,2,NaN,NaN,NaN,0,0,1,391,0,0,0
4,67,2,1,60.555587,3000.0,0.0,0,0,10,3280,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1369,1900,2,0,NaN,NaN,NaN,0,0,1,153,0,0,0
1370,0,0,0,1.945701,40.0,0.0,12,0,2,152,0,0,0
1371,0,0,0,1.024087,40.0,0.0,12,0,2,152,0,0,0
1372,0,0,0,59.390351,80.0,0.0,12,0,4,304,0,0,0
1373,0,0,0,NaN,NaN,NaN,12,0,1,76,0,0,0

In [33]:
import pandas as pd
import numpy as np

# Assuming df is your loaded DataFrame

# Calculate medians for non-S0 connections
non_s0_mask = df['conn_state'] != 0
medians = {
    'duration': df.loc[non_s0_mask, 'duration'].median(),
    'orig_bytes': df.loc[non_s0_mask, 'orig_bytes'].median(),
    'resp_bytes': df.loc[non_s0_mask, 'resp_bytes'].median()
}

# Only fill NaN values where conn_state == 0
for col in ['duration', 'orig_bytes', 'resp_bytes']:
    # For conn_state == 0: Fill ONLY NaNs with 0
    df.loc[(df['conn_state'] == 0) & (df[col].isna()), col] = 0
    
    # For conn_state != 0: Fill NaNs with their respective medians
    df.loc[(df['conn_state'] != 0) & (df[col].isna()), col] = medians[col]

# Verify the results
print("NaN values after imputation:")
print(df[['duration', 'orig_bytes', 'resp_bytes']].isna().sum())

NaN values after imputation:
duration      0
orig_bytes    0
resp_bytes    0
dtype: int64

In [34]:
df['Label'].isnull().values.any()

False

In [35]:
df

,id.resp_p,proto,service,duration,orig_bytes,resp_bytes,conn_state,missed_bytes,orig_pkts,orig_ip_bytes,resp_pkts,resp_ip_bytes,Label
0,67,2,1,8.322388,600.0,0.0,0,0,2,656,0,0,0
1,5353,2,2,0.000000,0.0,0.0,0,0,1,391,0,0,0
2,5353,2,2,0.000000,0.0,0.0,0,0,1,411,0,0,0
3,5353,2,2,0.000000,0.0,0.0,0,0,1,391,0,0,0
4,67,2,1,60.555587,3000.0,0.0,0,0,10,3280,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1369,1900,2,0,0.000000,0.0,0.0,0,0,1,153,0,0,0
1370,0,0,0,1.945701,40.0,0.0,12,0,2,152,0,0,0
1371,0,0,0,1.024087,40.0,0.0,12,0,2,152,0,0,0
1372,0,0,0,59.390351,80.0,0.0,12,0,4,304,0,0,0
1373,0,0,0,0.055029,47.0,111.0,12,0,1,76,0,0,0

In [36]:
import pandas as pd

# Check for NaN values in the current DataFrame
nan_check = df.isna().sum()

# Filter to only show columns with NaN values
nan_columns = nan_check[nan_check > 0]

if nan_columns.empty:
    print("No NaN values found in the DataFrame")
else:
    print("Columns with NaN values and their counts:")
    for col, count in nan_columns.items():
        print(f"- {col}: {count} NaN values")
    
    print(f"\nTotal NaN values in DataFrame: {nan_check.sum()}")

No NaN values found in the DataFrame

In [37]:
df['missed_bytes'] = df['missed_bytes'].fillna(0)

In [38]:
df.to_csv(r"7cleaned.csv",index=False)